custom.properties.path=

application.name=Formuvia

database.url=jdbc:postgresql://localhost:5432/formuvia
database.username=formuvia
database.password=formuvia
database.num.connections=20
database.check.query=select 1

forward.ip-adress.header=X-Real-IP

database.additional.shema=public

execute.scripts=true

admin.default.password=admin

#en-US, sr-Latn-RS, sr-RS
default.language=en-US

cookie.access.token.name=access_token
cookie.access.token.duration.minutes=10
cookie.refresh.token.duration.minutes=10080

#true, false
cookie.secure=true

#true, false
cookie.http.only=true

#Strict, Lax, None
cookie.same.site=Strict

cookie.path=/

cors.url=http://localhost:4200

database.listen.cron=*/2 * * * * ?
database.listen.connection.check.cron=0 */1 * * * ?
token.clear.cron=0 0 */1 * * ?
quartz.database.start=true

excel.date.format=dd.MM.yyyy
excel.date-time.format=dd.MM.yyyy HH:mm